name = "Examples"
uuid = "a60229a6-2119-4702-9088-6d2bb886a221"
authors = ["TT <tobias.thummerer@informatik.uni-augsburg.de>"]
version = "0.1.0"

[deps]
FMI = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"
FMIBuild = "226f0e26-6dd6-4589-ada7-1d32f6e1d800"
FMICore = "8af89139-c281-408e-bce2-3005eb87462f"
FMIExport = "31b88311-cab6-44ed-ba9c-fe5a9abbd67a"
FMIZoo = "724179cf-c260-40a9-bd27-cccc6fe2f195"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"