name = "Examples"

[deps]
FMIBuild = "226f0e26-6dd6-4589-ada7-1d32f6e1d800"
FMIExport = "31b88311-cab6-44ed-ba9c-fe5a9abbd67a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"

[compat]
FMIBuild = "0.4"
julia = "1.6"
